### PR TITLE
Adds JOSM how to add WMS server

### PR DESCRIPTION
**Pull request by bgirardot**

### CODE REVIEW

**Comment by Nick-Tallguy** [comment]
Glad I started this - I've learnt a lot.

**Comment by Nick-Tallguy** [comment]
@bgirardot I've amended this again, and deliberately very slightly completely obscured one of the characters in the url link in the screenshot. If you attempted to load the imagery by typing out the link as it appears on the screen, it would fail. 

If this is okay I will add it to the main site. I noticed that http://tasks.hotosm.org/project/2142 is suffering from the same problem with the link needing to be added manually - was there an upgrade in TM2 which prompted these?

Nick

**Comment by bgirardot** [comment]
@Nick-Tallguy Hi Nick, #2142 properly auto-loads the imagery for me in iD and JOSM, is it not working for you in one of them?

**Comment by bgirardot** [comment]
Oh ya, it always displays the imagery link, maybe from before it or the editors supported automatically loading custom imagery.

**Pull request merged**
